import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parent / "complaints.db"
SCHEMA_PATH = Path(__file__).resolve().parent / "schema.sql"


def get_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    schema_sql = SCHEMA_PATH.read_text(encoding="utf-8")
    conn = get_connection()
    try:
        conn.executescript(schema_sql)
        conn.commit()
    finally:
        conn.close()


def save_complaint(complaint):
    conn = get_connection()
    try:
        conn.execute(
            """
            INSERT OR REPLACE INTO complaints (
                unique_key, created_date, closed_date, agency, complaint_type,
                descriptor, incident_zip, status, severity, traffic_impact,
                public_impact, weather_risk, days_pending, frequency_count,
                complaint_frequency, safety_risk, priority_score, priority_category
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                complaint.get("unique_key"),
                complaint.get("created_date"),
                complaint.get("closed_date"),
                complaint.get("agency"),
                complaint.get("complaint_type"),
                complaint.get("descriptor"),
                complaint.get("incident_zip"),
                complaint.get("status"),
                complaint.get("severity"),
                complaint.get("traffic_impact"),
                complaint.get("public_impact"),
                complaint.get("weather_risk"),
                complaint.get("days_pending"),
                complaint.get("frequency_count"),
                complaint.get("complaint_frequency"),
                complaint.get("safety_risk"),
                complaint.get("priority_score"),
                complaint.get("priority_category"),
            ),
        )
        conn.commit()
    finally:
        conn.close()


def get_complaint_by_key(unique_key):
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT * FROM complaints WHERE unique_key = ?",
            (unique_key,),
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def save_work_order(work_order_id, complaints):
    conn = get_connection()
    try:
        conn.execute(
            "INSERT OR REPLACE INTO work_orders (work_order_id, status, notes) VALUES (?, ?, ?)",
            (work_order_id, "pending", "generated by optimization step"),
        )

        for queue_position, complaint in enumerate(complaints, start=1):
            conn.execute(
                """
                INSERT OR REPLACE INTO work_order_items (
                    work_order_id, complaint_unique_key, queue_position,
                    priority_score, safety_risk, status
                ) VALUES (?, ?, ?, ?, ?, ?)
                """,
                (
                    work_order_id,
                    complaint.get("unique_key"),
                    queue_position,
                    complaint.get("priority_score"),
                    complaint.get("safety_risk"),
                    "pending",
                ),
            )

        conn.commit()
    finally:
        conn.close()


def get_work_order(work_order_id):
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT * FROM work_orders WHERE work_order_id = ?",
            (work_order_id,),
        ).fetchone()
        if not row:
            return None

        items = conn.execute(
            "SELECT * FROM work_order_items WHERE work_order_id = ? ORDER BY queue_position",
            (work_order_id,),
        ).fetchall()
        return {"header": dict(row), "items": [dict(item) for item in items]}
    finally:
        conn.close()


if __name__ == "__main__":
    init_db()
    print(f"Database initialized at: {DB_PATH}")
